server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.140.222:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.140.223
    virtual-host: /zws
    username: zws
    password: zws
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000
logging:
  level:
    com.atguigu.gmall: debug