server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.140.223
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
threadPool:
  corePoolSize: 100
  maximumPoolSize: 500
  keepAliveTime: 60
  blockingSize: 5000